app:
  name: mq

logger:
  file: mq.log
  format: text
  level: info
  maxSize: 256
  maxAge: 3
  maxBackups: 7

rabbit:
  amqp: amqp://admin:admin@localhost:5672
  prefetch: 1
  deliveryMode: 2

rabbitQueue:
  simple:
    name: test-simple
    goroutines: 3
  topic:
    exchange: test-topic
    name: test-topic-log
    goroutines: 3
    routingKeys:
      - '#'

kafka:
  servers: kafka-online1:9092,kafka-online2:9092,kafka-online3:9092
  compress: lz4
  logger: true
  write:
    async: true
  read:
    offset: last
    commitInterval: 1
    MaxBytes: 102400
  sasl:
    enable: false
    mechanism: PLAIN
    username: admin
    password: admin

kafkaQueue:
  topic: test-topic
  groupId: test-topic-group
  goroutines: 2
