app:
  name: mq

logger:
  file: mq.log
  format: text
  level: info
  maxSize: 256
  maxAge: 3
  maxBackups: 7

rabbit:
  amqp: amqp://admin:admin@localhost:5672
  prefetch: 5
  deliveryMode: 2

rabbitQueue:
  simple:
    name: go-simple
    goroutines: 3
  topic:
    exchange: go-topic
    name: go-topic-log
    goroutines: 3
    routingKeys:
      - '#'

kafka:
  servers:
    - kafka-online1:9092
    - kafka-online2:9092
    - kafka-online3:9092
  compress: lz4
  write:
    async: true
  read:
    offset: last
    commitInterval: 0
    MaxBytes: 4096000
  sasl:
    enable: false
    mechanism: PLAIN
    username: admin
    password: 08afd6f9ae0c6017d105b4ce580de885

kafkaQueue:
  topic: go-test
  groupId: go-test-group
  goroutines: 3
